idf_component_register(
    SRCS
        "main.c"
        "wifi_manager.c"
        "audio_pipeline.c"
        "airplay_server.c"
        "dlna_renderer.c"
        "http_streamer.c"
        "dsp_eq.c"
        "ota_engine.c"
        "web_server.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        mdns
        esp_wifi
        esp_event
        nvs_flash
        esp_http_server
        esp_http_client
        esp_partition
        app_update
        driver
        esp_netif
        mbedtls
        lwip
        esp_ringbuf
        esp_psram
        esp_timer
        esp_system
        heap
        freertos
        json
    PRIV_REQUIRES
        mdns
        json
        esp_psram
        esp_event
        esp_ringbuf
        esp_http_server
        esp_http_client
        esp_partition
        app_update
        mbedtls
        lwip
        esp_wifi
        nvs_flash
        driver
        heap
        esp_timer
        esp_system
        freertos
)
